### ISSUE TITLE
Error in tileset

### ISSUE THREAD

**Issue by SimonStoyanov** [Trodek/Project-1-Team-SUMHC-Pro-Name#11]
![image](https://cloud.githubusercontent.com/assets/17119542/14982376/30abb058-1136-11e6-9056-d6b8c8916d24.png)

![image](https://cloud.githubusercontent.com/assets/17119542/14982389/403a47d2-1136-11e6-93bd-95eba3b3e04c.png)

**Comment by sergipa** [comment]
We no longer do lvl 2
