### ISSUE TITLE
If you press shoot and bomb you can only move forwards while shooting.

### ISSUE THREAD

**Issue by rcpauor32** [Trodek/Project-1-Team-SUMHC-Pro-Name#15]
**Steps to Reproduce:** Press shoot ('f') and bomb ('g') at the same time at any point. Then you can only go forwards, and the player keeps shootinf lasers as if you where just repeating the shooting key.

**Actual behaviour:** Player Shoots but cannot move forwards.
**Expected behaviour:** Player should be able to move while shooting.

**Comment by sergipa** [comment]
SDL doesn't support more than 3 keys at the same time
