### ISSUE TITLE
If you keep pressing the shoot button with multi-laser it shoots 2 times almost at the same time

### ISSUE THREAD

**Issue by Andreu997** [Trodek/Project-1-Team-SUMHC-Pro-Name#17]
### Actual behavior

If the shooting button is keep pressed while the multi-laser is equiped, two lasers are shooted almost at the same time and after that, it shoots once every 1-2 seconds
### Steps to reproduce the behavior

just keep pressed the shoot button while holding the multi-laser

**Comment by sergipa** [comment]
Solved
