### ISSUE TITLE
Tank explosion doesn't kill you

### ISSUE THREAD

**Issue by IVREI0T** [Trodek/Project-1-Team-SUMHC-Pro-Name#20]
### Expected behaviour

If you walk into the tank explosion, you should die. Since it's an explosion.
### Actual behaviour

The explosion doesn't kill you. I suspect that there's no particle collider in that particular explosion?
### Steps to reproduce that behaviour

Kill the tank and step into the exploding particles

**Comment by sergipa** [comment]
Works as intended, in the real game it works like that
