### ISSUE TITLE
During boss after dying nothing happens

### ISSUE THREAD

**Issue by d0n3val** [Trodek/Project-1-Team-SUMHC-Pro-Name#27]
Prio B
Repro, progress to the boss and die because you coolide whit the boss
Note: The player explosion is bugged and very quicly you see a wrong animation

![image](https://cloud.githubusercontent.com/assets/627698/15387163/d903cc14-1dab-11e6-80de-c94b3a052942.png)

**Comment by sergipa** [comment]
Solved
