### ISSUE TITLE
Enemies

### ISSUE THREAD

**Issue by SimonStoyanov** [Trodek/Project-1-Team-SUMHC-Pro-Name#8]
At this position the turrets can not hit you, but you are not god.
BLASFEMIA!

![image](https://cloud.githubusercontent.com/assets/17119542/14982273/8e46fbf6-1135-11e6-8bb2-e59334562d0e.png)

![image](https://cloud.githubusercontent.com/assets/17119542/14982275/9351c0e0-1135-11e6-9e36-adb89b2ac5f0.png)

![image](https://cloud.githubusercontent.com/assets/17119542/14982286/9af63308-1135-11e6-837f-528baaa6cc2b.png)

**Comment by sergipa** [comment]
We no longer do lvl 1
